feat: pool deployment
TyroML/backend pull request #108
Opened 2023-07-26 19:33 UTC by TheRealSeber

2023-07-28 08:59 UTC, HermanPlay requested changes
Small changes needed

2023-07-28 08:59 UTC, HermanPlay commented on app/api/routers/pool.py
> +    Deploy the pool with the given ID.
Documentation differs from the actual functionality

2023-07-28 08:59 UTC, HermanPlay commented on app/api/services/pool.py
> +        Deploys a pool.
Documentation different from the actual functionality

2023-07-28 15:07 UTC, merged

2023-07-29 08:55 UTC, TheRealSeber commented on app/api/charts/pool/templates/virtualservice.yaml
> +        prefix: "/{{ .Values.prefix }}"
why did you write the same thing twice?

2023-07-29 08:58 UTC, matined commented on app/api/charts/pool/templates/virtualservice.yaml
> +        prefix: "/{{ .Values.prefix }}"
it's not the same thing