gateaway and virtualservice yaml generators
TyroML/backend pull request #77
Opened 2023-05-30 13:48 UTC by TheRealSeber

brak śmietnika, pdw

2023-05-30 20:41 UTC, matined requested changes
it's gateway not gateaway :))

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +    def __init__(self, pools: list[pool_schemas.Pool], gateaway_name: str) -> None:
let's pass `name: str` and `pools: list[gate_schemas.GatePool]` as parameters

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +                "number": Constants.K8S_DEPLOYMENT_PORT,
create a new constant to ISTIO_GATEWAY_PORT

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +                "namespace": f"gateaway-config-{self.name}",
why not `models`

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +            "metadata": {"name": self.name, "namespace": f"pool-config-{self.name}"},
put namespace in a new line and set to `models`

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +                    "port": {"number": Constants.K8S_SERVICE_PORT},
create a new ISTIO_VIRTUAL_SERVICE_PORT contant for it

2023-05-30 20:41 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +    def __init__(
change the list of params to `name: str`, `gateway_names: list[str]` and `models: list[pool_model_schemas.PoolModel]`

2023-05-31 10:32 UTC, TheRealSeber commented on app/api/utils/istio_manifest_generator.py
> +            "metadata": {"name": self.name, "namespace": f"pool-config-{self.name}"},
tell it to black and flake8

2023-05-31 10:37 UTC, TheRealSeber commented on app/api/utils/istio_manifest_generator.py
> +    def __init__(
why do we want to pass list of gateways? virtual service is in the pool namespace and there is  only one, certain gateaway "above" the pool

2023-05-31 10:39 UTC, TheRealSeber commented on app/api/utils/istio_manifest_generator.py
> +                "namespace": f"gateaway-config-{self.name}",
because it doesn't change anything and this namespace is much more readable imo. see istio dosc on gateway. later on virtual service is attached to the given gateway by the namespace.

2023-07-02 19:09 UTC, TheRealSeber commented
<img width="356" alt="image" src="https://github.com/MLOps-KNDS/backend/assets/111927572/c664a712-308f-4995-a195-8141b69e5277">
<img width="346" alt="image" src="https://github.com/MLOps-KNDS/backend/assets/111927572/5e11fe1f-05ef-4788-8ca0-4e4aa1c64f40">

2023-07-03 18:20 UTC, matined approved these changes
Great, let's merge it and we'll

2023-07-03 18:20 UTC, matined commented on app/api/utils/pool_deployment.py
> +            namespace=f"pool-config-{self.name}",
let's change namespace to `Constants.K8S_NAMESPACE_MODELS` and we'll merge it

2023-07-12 10:48 UTC, HermanPlay commented
Please Mr S, proceed to do something, me and Mr Nedzie are waiting

2023-07-12 21:27 UTC, TheRealSeber commented
Temporarily (or not) I have created a router for the Istio gateway and virtual service deployment.

Also i moved istio gateway and virtual services to the distinct namespaces to make the kubernetes more transparent.

2023-07-14 09:05 UTC, TheRealSeber commented
> Please Mr S, proceed to do something, me and Mr Nedzie are waiting

I proceeded to do something

2023-07-14 10:40 UTC, HermanPlay requested changes
Please be careful with project secrets, and try not to share them next time.

2023-07-14 10:40 UTC, HermanPlay commented on app/api/utils/istio_manifest_generator.py
> +        pool_models: list[pool_model_schemas.PoolModelDetailed],
Since we are changing DB, I think we should change the schema. From now we will only have pools records, and you would have to modify your code accordingly.

2023-07-14 10:40 UTC, HermanPlay commented on docker-compose.yml
> +    #   - /usr/bin/docker:/usr/bin/docker
Uncomment this before merge pls

2023-07-14 10:40 UTC, HermanPlay commented on docker-compose.yml
> +      - GOOGLE_CLIENT_SECRET=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
Thanks for sharing out secrets 😁. Please remove this.

2023-07-19 18:50 UTC, HermanPlay requested changes
If generaly code works, just answer my questions or fix the issues.

2023-07-19 18:50 UTC, HermanPlay commented on app/api/routers/pool_model.py
> +    return await PoolService.patch_pool_models(db=db, pool_id=pool_id, details=details)
Add getting user id from bearer, and updating necessary fields in db

2023-07-19 18:50 UTC, HermanPlay commented on app/api/utils/__init__.py
> +from utils.deployments.model_deployment import ModelDeployment  # noqa: F401
If you added `ModelDeployment` to `utils.deployment` `__init__.py` file, than why dont you import like this:
`from utils.deployments import ModelDeployment`?

2023-07-19 18:50 UTC, HermanPlay commented on app/api/utils/deployments/pool_deployment.py
> +from utils.generators.istio_virtual_service import IstioVirtualServiceGenerator
Why not importing like this: `from utils.generators import IstioVirtualServiceGenerator`?

2023-07-19 19:47 UTC, TheRealSeber commented on app/api/utils/deployments/pool_deployment.py
> +        except Exception:
this is just pain for my eyes. btw you don't even use the Exception object so no need to even writing it after "except" keyword

2023-07-19 19:47 UTC, TheRealSeber commented on app/api/routers/pool.py
> +    await PoolService.delete_pool(db=db, pool_id=pool_id)
before deleting the pool, we should also make sure to delete virtual service for the given pool.

2023-07-19 21:43 UTC, merged

2023-07-20 10:54 UTC, TheRealSeber commented
git commit --amend --no-edit